# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-jsonschema" do
  version "0.24.1"

  on_macos do
    on_intel do
      sha256 "c54d0de2d9331c8e5bd421299d9cc292956d011bf3f7f8c2e3ab8e96d20bd3ec"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Darwin_x86_64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
    on_arm do
      sha256 "22f0881b06952c5c0fb94cd2000ce98f53de3a0efeb505c3c1a2d0da79fa8c13"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Darwin_arm64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
  end

  on_linux do
    on_intel do
      sha256 "a486718d9041114449eaf2a422eae46d29337421fee80325a1c481a5126b78c8"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Linux_x86_64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
    on_arm do
      sha256 "c59b7c04a4f475d9d23c5ce3aaa263b42ee02eb3a21ff044616effa2bfeca9ec"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Linux_arm64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
  end

  name "go-jsonschema"
  desc "go-jsonschema binary"
  homepage "https://github.com/omissis/go-jsonschema"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-jsonschema"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-jsonschema"]
    end
  end

  # No zap stanza required

end
