# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-jsonschema" do
  version "0.24.0"

  on_macos do
    on_intel do
      sha256 "e4b1ca05bac2db8acbf87c98219d3eace85fe18cb7cd75e44d7644e6f8a70bea"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Darwin_x86_64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
    on_arm do
      sha256 "5d76b5f0dc07b1d32bd53c82470c6d187b99c7733021bf674e4e77e6cdd24726"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Darwin_arm64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
  end

  on_linux do
    on_intel do
      sha256 "2349aff75bf77d58ccf1c0393f1161ae529267ceab804a857133dd6b56618607"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Linux_x86_64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
    on_arm do
      sha256 "316ee052afb388654d1cb13101d8ffa5c19303d726eb2c0125835aede345267e"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Linux_arm64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
  end

  name "go-jsonschema"
  desc "go-jsonschema binary"
  homepage "https://github.com/omissis/go-jsonschema"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-jsonschema"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-jsonschema"]
    end
  end

  # No zap stanza required

end
