# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-jsonschema" do
  version "0.23.1"

  on_macos do
    on_intel do
      sha256 "5387176bdbfd41e0d2a499e6792cb46e69d249e60a9016d54bf89497c6c03335"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Darwin_x86_64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
    on_arm do
      sha256 "edfab60d655dad0fe083a60a08164bf0197be606a5a1af3bedac963a4b69a5ac"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Darwin_arm64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
  end

  on_linux do
    on_intel do
      sha256 "652b26898c0cd27eaca234d7ac73c1d02c87e99112dd65be3f17083ded7368dc"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Linux_x86_64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
    on_arm do
      sha256 "084d65f5f27a26d4fa07ab6d864ca1e742cd9aab0c78f92a6b5f3d503994c097"
      url "https://github.com/omissis/go-jsonschema/releases/download/v#{version}/go-jsonschema_Linux_arm64.tar.gz",
        verified: "github.com/omissis/go-jsonschema"
    end
  end

  name "go-jsonschema"
  desc "go-jsonschema binary"
  homepage "https://github.com/omissis/go-jsonschema"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-jsonschema"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-jsonschema"]
    end
  end

  # No zap stanza required

end
