# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoJsonschema < Formula
  desc "go-jsonschema binary"
  homepage "https://gihub.com/omissis/go-jsonschema"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/omissis/go-jsonschema/releases/download/v0.10.0/go-jsonschema_0.10.0_Darwin_arm64.tar.gz"
      sha256 "5d89b4c184dd5038957ca2da0948762ad1fe5ba96b83973b3e7799214d4e0f86"

      def install
        bin.install 'go-jsonschema'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/omissis/go-jsonschema/releases/download/v0.10.0/go-jsonschema_0.10.0_Darwin_x86_64.tar.gz"
      sha256 "a070b985590cd7282e7d8c238b9c404cb4621d2b0cd163cccc58a5ea34a4dd10"

      def install
        bin.install 'go-jsonschema'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/omissis/go-jsonschema/releases/download/v0.10.0/go-jsonschema_0.10.0_Linux_x86_64.tar.gz"
      sha256 "e4b2a257ca2e2dc193f38564e46bfd4ee69f749f4213bbb41ab4531b70a86c5a"

      def install
        bin.install 'go-jsonschema'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/omissis/go-jsonschema/releases/download/v0.10.0/go-jsonschema_0.10.0_Linux_arm64.tar.gz"
      sha256 "21fd1dd19bc1bbf1db90bb10db14ac39339ee9424b59621786034e40fb91a5e1"

      def install
        bin.install 'go-jsonschema'
      end
    end
  end

  test do
    system "#{bin}/go-jsonschema"
  end
end
